"use client";
import Image from "next/image";
import { useMemo, useState } from "react";
import { formatAssetAmount, getAssetById } from "@/lib/assets";
import { shortAddress } from "@/lib/format";
import { filterActivity, type ActivityFilter } from "@/lib/indexer/filter";
import { activityIdentity } from "@/lib/onchainActivity";
import { arcScanTransactionUrl, type WalletActivity } from "@/lib/wallet";
import styles from "./MakotoWallet.module.css";

type Props = { activities: WalletActivity[]; locale: "en" | "vi"; limit: number; loading: boolean; loadingMore: boolean; partial: boolean; unavailable: boolean; canLoadMore: boolean; onClose(): void; onLoadMore(): void; onRefresh(): void; onReceipt(activity: WalletActivity): void };

export function ActivityHistoryPanel({ activities, locale, limit, loading, loadingMore, partial, unavailable, canLoadMore, onClose, onLoadMore, onRefresh, onReceipt }: Props) {
  const vi = locale === "vi", [filter, setFilter] = useState<ActivityFilter>("all"), [search, setSearch] = useState("");
  const filtered = useMemo(() => filterActivity(activities, filter, search), [activities, filter, search]);
  const filters: ActivityFilter[] = ["all", "send", "receive", "swap", "bridge", "vault"];
  return <div className={styles.activityHistoryLayer} role="dialog" aria-modal="true" aria-labelledby="activity-history-title"><button type="button" className={styles.activityHistoryBackdrop} onClick={onClose} aria-label={vi ? "Đóng" : "Close"} /><section className={styles.activityHistoryPanel}>
    <header><div><small>Arc Testnet · {partial ? (vi ? "Lịch sử một phần" : "Partial history") : (vi ? "Đã đồng bộ on-chain" : "Synced on-chain")}</small><h2 id="activity-history-title">{vi ? "Toàn bộ hoạt động" : "All Activity"}</h2></div><div className={styles.activityHeaderActions}><button type="button" onClick={onRefresh} disabled={loading}>{vi ? "Làm mới" : "Refresh"}</button><button type="button" onClick={onClose} aria-label={vi ? "Đóng" : "Close"}>×</button></div></header>
    <div className={styles.activityTools}><div className={styles.activityFilters}>{filters.map((value) => <button type="button" key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{filterLabel(value, vi)}</button>)}</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={vi ? "Tìm hash hoặc địa chỉ" : "Search hash or address"} aria-label={vi ? "Tìm hoạt động" : "Search activity"} /></div>
    {loading && activities.length === 0 ? <div className={styles.activitySkeleton} aria-label={vi ? "Đang tải hoạt động" : "Loading activity"}>{Array.from({ length: 5 }, (_, index) => <span key={index} />)}</div> : unavailable && activities.length === 0 ? <p className={styles.activityPartialWarning}>{vi ? "Lịch sử on-chain tạm thời không khả dụng. Hãy thử Làm mới sau." : "On-chain history is temporarily unavailable. Please try Refresh again."}</p> : activities.length === 0 ? <div className={styles.emptyActivity}><strong>{vi ? "Chưa có hoạt động" : "No activity yet"}</strong><span>{vi ? "Giao dịch Arc được hỗ trợ sẽ xuất hiện tại đây sau khi xác nhận." : "Supported Arc transactions will appear here after confirmation."}</span></div> : <>{partial && <p className={styles.activityPartialWarning}>{unavailable ? (vi ? "Lịch sử on-chain tạm thời không khả dụng. Hoạt động đã xác nhận cục bộ vẫn được hiển thị." : "On-chain history is temporarily unavailable. Valid locally confirmed activity is still shown.") : (vi ? "Đang hiển thị hoạt động gần đây từ Arc RPC. Lịch sử một phần." : "Showing recent activity from Arc RPC. Partial history.")}</p>}{filtered.length === 0 ? <div className={styles.emptyActivity}><strong>{vi ? "Không có kết quả" : "No matching activity"}</strong></div> : <ul className={styles.activityList}>{filtered.slice(0, limit).map((item) => <ActivityRow key={activityIdentity(item)} item={item} locale={locale} onReceipt={onReceipt} />)}</ul>}{canLoadMore && <button type="button" className={styles.activityLoadMore} onClick={onLoadMore} disabled={loadingMore}>{loadingMore ? (vi ? "Đang tải…" : "Loading…") : (vi ? "Tải thêm" : "Load more")}</button>}</>}
  </section></div>;
}
function ActivityRow({ item, locale, onReceipt }: { item: WalletActivity; locale: "en" | "vi"; onReceipt(activity: WalletActivity): void }) { const vi = locale === "vi", asset = getAssetById(item.assetId)!, amount = formatAssetAmount(item.amount, asset); const title = item.kind === "swap" && item.swapReceive ? `${vi ? "Hoán đổi" : "Swap"} -${amount} ${item.assetSymbol} → +${formatAssetAmount(item.swapReceive.amount, getAssetById(item.swapReceive.assetId)!)} ${item.swapReceive.assetSymbol}` : `${kindLabel(item, vi)} ${item.direction === "receive" ? "+" : "-"}${amount} ${item.assetSymbol}`; const detail = item.kind === "swap" ? "XyloNet StableSwap" : item.kind === "bridge" ? "Arc → Base · CCTP V2" : item.kind === "vault-deposit" || item.kind === "vault-withdraw" ? "Makoto Vault" : `${item.direction === "receive" ? (vi ? "Từ" : "From") : (vi ? "Đến" : "To")} ${shortAddress(item.counterparty)}`; return <li><Image src={item.kind === "swap" ? "/makoto/icon-swap-pro-v2.png" : item.direction === "receive" ? "/makoto/icon-receive-pro-v2.png" : "/makoto/icon-send-pro-v2.png"} alt="" width={54} height={54} className={styles.activityIcon} /><div className={styles.activityMain}><strong>{title}</strong><small>{detail} · {formatTime(item.confirmedAt, locale)}</small></div><span className={styles.activityStatus}>{item.source === "local" ? (vi ? "Đã xác nhận · ghi nhận cục bộ" : "Confirmed · locally observed") : (vi ? "Đã xác nhận" : "Confirmed")}</span><div className={styles.activityActions}>{item.source !== "onchain" && <button type="button" onClick={() => onReceipt(item)}>{vi ? "Biên nhận" : "Receipt"}</button>}<a href={arcScanTransactionUrl(item.hash)} target="_blank" rel="noreferrer" className={styles.activityLink}>ArcScan ↗</a></div></li>; }
function kindLabel(item: WalletActivity, vi: boolean) { if (item.kind === "bridge") return vi ? "Chuyển chuỗi" : "Bridge"; if (item.kind === "vault-deposit") return vi ? "Nạp Makoto Vault" : "Makoto Vault Deposit"; if (item.kind === "vault-withdraw") return vi ? "Rút Makoto Vault" : "Makoto Vault Withdraw"; return item.direction === "receive" ? (vi ? "Nhận" : "Receive") : (vi ? "Gửi" : "Send"); }
function filterLabel(filter: ActivityFilter, vi: boolean) { const en = { all: "All", send: "Send", receive: "Receive", swap: "Swap", bridge: "Bridge", vault: "Vault" }, vn = { all: "Tất cả", send: "Gửi", receive: "Nhận", swap: "Hoán đổi", bridge: "Bridge", vault: "Vault" }; return (vi ? vn : en)[filter]; }
function formatTime(timestamp: number, locale: "en" | "vi") { return new Intl.DateTimeFormat(locale === "vi" ? "vi-VN" : "en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(timestamp)); }
