import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { webcrypto } from "node:crypto";
import { APP_LOCK_SESSION_KEY, APP_LOCK_SESSION_MARKER, APP_LOCK_SIGNAL_KEY, APP_LOCK_STORAGE_KEY, canGrantAppLockSession, clearMakotoConvenienceData, cooldownDuration, createAppLockConfig, hasAuthenticatedAppLockSession, inactivityExpired, initialAppLockState, isMatchingAppLockSessionGrant, isValidPin, isWeakPin, parseAppLockConfig, parseAppLockSessionMessage, pinsMatch, recordFailedAttempt, resetFailedAttempts, syncAppLockStorageEvent, verifyAppLockPin, type AppLockConfig, type AppLockSessionState } from "./appLock.ts";
import { appLockRecommendation } from "./securityCenter.ts";

const cryptoApi = webcrypto as unknown as Crypto;
test("PIN validation requires six numeric digits and detects weak forms", () => { assert.equal(isValidPin("123456"), true); assert.equal(isValidPin("12345"), false); assert.equal(isValidPin("1234567"), false); assert.equal(isValidPin("12a456"), false); assert.equal(pinsMatch("246810", "246810"), true); assert.equal(pinsMatch("246810", "246811"), false); assert.equal(isWeakPin("000000"), true); assert.equal(isWeakPin("111111"), true); assert.equal(isWeakPin("123456"), true); assert.equal(isWeakPin("654321"), true); assert.equal(isWeakPin("246810"), false); });
test("PBKDF2 stores no raw PIN, verifies correctly, and PIN change creates a new salt", async () => { const first = await createAppLockConfig("246810", 300_000, cryptoApi); const second = await createAppLockConfig("135790", 300_000, cryptoApi); assert.notEqual(first.salt, second.salt); assert.notEqual(first.verifier, second.verifier); assert.equal(JSON.stringify(first).includes("246810"), false); assert.equal(await verifyAppLockPin("246810", first, cryptoApi), true); assert.equal(await verifyAppLockPin("246811", first, cryptoApi), false); assert.deepEqual(parseAppLockConfig(JSON.stringify(first)), first); });
test("manual/reload/inactivity state and cooldown helpers are deterministic", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); assert.ok(parseAppLockConfig(JSON.stringify(config))); assert.equal(inactivityExpired(1_000, 60_000, 60_999), false); assert.equal(inactivityExpired(1_000, 60_000, 61_000), true); assert.equal(inactivityExpired(1_000, 0, 999_999), false); let failed = config; for (let count = 0; count < 5; count += 1) failed = recordFailedAttempt(failed, 1_000); assert.equal(failed.cooldownUntil, 31_000); assert.equal(failed.failedAttempts, 0); assert.equal(cooldownDuration(99), 900_000); assert.deepEqual({ failedAttempts: resetFailedAttempts(failed).failedAttempts, cooldownUntil: resetFailedAttempts(failed).cooldownUntil }, { failedAttempts: 0, cooldownUntil: 0 }); });
test("cross-tab configuration changes preserve an unlocked session", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); const never = { ...config, autoLockMs: 0 }; assert.deepEqual(syncConfig(unlocked(config), never), unlocked(never)); });
test("cross-tab manual Lock now locks an enabled session", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); assert.deepEqual(syncSignal(unlocked(config), config, "lock"), { config, locked: true }); });
test("cross-tab PIN changes update config without locking an unlocked session", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); const changed = await createAppLockConfig("135790", 60_000, cryptoApi); assert.deepEqual(syncConfig(unlocked(config), changed), unlocked(changed)); });
test("cross-tab cooldown bookkeeping does not lock an unrelated session", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); const cooldown = { ...config, failedAttempts: 0, cooldownLevel: 1, cooldownUntil: 31_000 }; assert.deepEqual(syncConfig(unlocked(config), cooldown), unlocked(cooldown)); });
test("cross-tab disable clears config and unlocks", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); assert.deepEqual(syncSignal({ config, locked: true }, undefined, "disable"), { config: undefined, locked: false }); });
test("cross-tab reset clears config and unlocks", async () => { const config = await createAppLockConfig("246810", 60_000, cryptoApi); assert.deepEqual(syncSignal({ config, locked: true }, undefined, "reset"), { config: undefined, locked: false }); });
test("hard reload starts locked when App Lock is enabled", async () => { const config = await createAppLockConfig("246810", 0, cryptoApi); assert.deepEqual(initialAppLockState(JSON.stringify(config)), { config, locked: true }); assert.deepEqual(initialAppLockState(null), { config: undefined, locked: false }); });
test("legacy v1 config migrates without losing PIN state and session convenience defaults off", async () => { const current = await createAppLockConfig("246810", 300_000, cryptoApi); const legacy = JSON.parse(JSON.stringify(current)) as Record<string, unknown>; delete legacy.keepUnlockedSession; const migrated = parseAppLockConfig(JSON.stringify(legacy)); assert.ok(migrated); assert.equal(migrated.verifier, current.verifier); assert.equal(migrated.salt, current.salt); assert.equal(migrated.failedAttempts, current.failedAttempts); assert.equal(migrated.cooldownUntil, current.cooldownUntil); assert.equal(migrated.keepUnlockedSession, false); assert.equal(await verifyAppLockPin("246810", migrated, cryptoApi), true); });
test("session-enabled config stays locked on cold start and unlocks only with an authenticated session", async () => { const config = { ...await createAppLockConfig("246810", 300_000, cryptoApi), keepUnlockedSession: true }; assert.equal(initialAppLockState(JSON.stringify(config), false).locked, true); assert.equal(initialAppLockState(JSON.stringify(config), true).locked, false); assert.equal(hasAuthenticatedAppLockSession(APP_LOCK_SESSION_MARKER), true); assert.equal(hasAuthenticatedAppLockSession("true"), false); });
test("new-tab grants require a live unlocked eligible peer and matching request", async () => { const config = { ...await createAppLockConfig("246810", 300_000, cryptoApi), keepUnlockedSession: true }; const request = parseAppLockSessionMessage({ type: "request-session-unlock", requestId: "request-12345678" }); assert.equal(canGrantAppLockSession(config, false, request), true); assert.equal(canGrantAppLockSession(config, true, request), false); assert.equal(canGrantAppLockSession({ ...config, keepUnlockedSession: false }, false, request), false); assert.equal(isMatchingAppLockSessionGrant("request-12345678", parseAppLockSessionMessage({ type: "grant-session-unlock", requestId: "request-12345678" })), true); assert.equal(isMatchingAppLockSessionGrant("another-request", parseAppLockSessionMessage({ type: "grant-session-unlock", requestId: "request-12345678" })), false); });
test("session messages reject secrets, malformed actions, and unmatched identifiers", () => { assert.equal(parseAppLockSessionMessage({ type: "grant-session-unlock", requestId: "short" }), undefined); assert.equal(parseAppLockSessionMessage({ type: "unlock", requestId: "request-12345678" }), undefined); assert.equal(parseAppLockSessionMessage(JSON.stringify({ type: "grant-session-unlock", requestId: "request-12345678" })), undefined); });
test("provider persists the toggle immediately and clears ephemeral markers for lock, disable, and reset", () => { const provider = readFileSync(new URL("../hooks/useAppLock.tsx", import.meta.url), "utf8"); assert.match(provider, /setKeepUnlockedSession[\s\S]*persist\(\{ \.\.\.config, keepUnlockedSession: value \}\)/); assert.match(provider, /const lock = useCallback\(\(\) => \{[^}]*writeSessionMarker\(false\)/); assert.match(provider, /const disable = useCallback[\s\S]*writeSessionMarker\(false\)/); assert.match(provider, /const reset = useCallback[\s\S]*writeSessionMarker\(false\)/); assert.match(provider, /inactivityExpired[\s\S]*lock\(\)/); });
test("changing session preference preserves cross-tab unlocked state", async () => { const config = await createAppLockConfig("246810", 300_000, cryptoApi); const enabled = { ...config, keepUnlockedSession: true }; assert.deepEqual(syncConfig(unlocked(config), enabled), unlocked(enabled)); assert.deepEqual(syncConfig(unlocked(enabled), config), unlocked(config)); });
test("session convenience never persists an unlocked flag or PIN in localStorage or cross-tab messages", () => { const provider = readFileSync(new URL("../hooks/useAppLock.tsx", import.meta.url), "utf8"); assert.equal(APP_LOCK_SESSION_KEY, "makoto-wallet:app-lock-session:v1"); assert.match(provider, /sessionStorage\.(?:setItem|removeItem)\(APP_LOCK_SESSION_KEY/); assert.doesNotMatch(provider, /localStorage\.setItem\([^\n]*(?:unlocked|authenticated)/i); assert.doesNotMatch(provider, /postMessage\([^\n]*(?:pin|verifier|salt)/i); assert.doesNotMatch(provider, /sessionStorage\.setItem\([^\n]*pin/i); });
test("initialization gate hides application content until session resolution", () => { const gate = readFileSync(new URL("../components/AppLockGate.tsx", import.meta.url), "utf8"); assert.match(gate, /if \(!appLock\.initialized\) return <main[^>]*aria-busy="true"/); assert.match(gate, /if \(!appLock\.locked\) return children/); assert.ok(gate.indexOf("if (!appLock.initialized)") < gate.indexOf("return children")); });
test("App Lock session UI is accessible, localized, responsive, and clarifies inactivity", () => { const settings = readFileSync(new URL("../components/AppLockSettings.tsx", import.meta.url), "utf8"); const css = readFileSync(new URL("../components/MakotoWallet.module.css", import.meta.url), "utf8"); const en = readFileSync(new URL("../i18n/en.ts", import.meta.url), "utf8"); const vi = readFileSync(new URL("../i18n/vi.ts", import.meta.url), "utf8"); assert.match(settings, /role="switch"/); assert.match(settings, /aria-checked=/); assert.match(settings, /aria-labelledby=/); assert.match(settings, /aria-describedby=/); assert.match(css, /\.appLockSwitch:focus-visible/); assert.match(css, /@media\(max-width:560px\)\{\.appLockSessionSetting/); assert.match(en, /Never due to inactivity/); assert.match(vi, /Không khóa khi không hoạt động/); for (const key of ["keepSession", "keepSessionDescription", "keepSessionSecurity", "on", "offState"]) { assert.match(en, new RegExp(`appLock\\.${key}`)); assert.match(vi, new RegExp(`appLock\\.${key}`)); } });
test("App Lock disabled status and storage disclosure each render exactly once", () => { const settings = readFileSync(new URL("../components/AppLockSettings.tsx", import.meta.url), "utf8"); assert.equal(settings.match(/t\("appLock\.off"\)/g)?.length, 1); assert.equal(settings.match(/t\("appLock\.storageDisclosure"\)/g)?.length, 2); assert.match(settings, /lock\.enabled && <div[^>]+settingsInfo[\s\S]*t\("appLock\.enabled"\)/); assert.match(settings, /!lock\.enabled && <div[^>]+securityAlert[\s\S]*t\("appLock\.storageDisclosure"\)/); assert.match(settings, /lock\.enabled && <p[^>]+settingsMuted[\s\S]*t\("appLock\.storageDisclosure"\)/); });
test("reset clears only selected Makoto convenience data and preserves PRIVATE metadata", () => { const storage = new MemoryStorage({ [APP_LOCK_STORAGE_KEY]: "lock", [APP_LOCK_SIGNAL_KEY]: "signal", "makoto-wallet:contacts:v1:a": "contacts", "makoto-wallet:recent-recipients:v1:a": "recents", "makoto-wallet:activity:v3:a": "activity", "pengujar:v3:private-metadata:v1": "encrypted", "reown:session": "wallet" }); clearMakotoConvenienceData(storage); assert.equal(storage.getItem(APP_LOCK_STORAGE_KEY), null); assert.equal(storage.getItem("makoto-wallet:contacts:v1:a"), null); assert.equal(storage.getItem("pengujar:v3:private-metadata:v1"), "encrypted"); assert.equal(storage.getItem("reown:session"), "wallet"); });
test("provider uses storage synchronization without broadcasting PIN and gate hides application content", () => { const provider = readFileSync(new URL("../hooks/useAppLock.tsx", import.meta.url), "utf8"); const gate = readFileSync(new URL("../components/AppLockGate.tsx", import.meta.url), "utf8"); assert.match(provider, /StorageEvent/); assert.match(provider, /APP_LOCK_SIGNAL_KEY/); assert.doesNotMatch(provider, /JSON\.stringify\(\{[^}]*pin/i); assert.match(gate, /if \(!appLock\.locked\) return children/); assert.match(gate, /app-lock-screen/); });
test("shared PIN field avoids login password semantics while retaining numeric masking", () => { const input = readFileSync(new URL("../components/AppLockPinInput.tsx", import.meta.url), "utf8"); const gate = readFileSync(new URL("../components/AppLockGate.tsx", import.meta.url), "utf8"); const settings = readFileSync(new URL("../components/AppLockSettings.tsx", import.meta.url), "utf8"); const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8"); for (const source of [input, gate, settings]) { assert.doesNotMatch(source, /type="password"/); assert.doesNotMatch(source, /autoComplete="(?:new|current)-password"/); } assert.match(input, /type="text"/); assert.match(input, /inputMode="numeric"/); assert.match(input, /autoComplete="off"/); assert.match(input, /data-form-type="other"/); assert.match(input, /pattern="\[0-9\]\{6\}"/); assert.match(input, /maxLength=\{6\}/); assert.match(input, /replace\(\/\\D\/g/); assert.match(input, /app-lock-pin-mask/); assert.match(css, /app-lock-pin-control>input[^}]*color:transparent/); assert.match(css, /app-lock-pin-mask i/); });
test("Forgot PIN is available only after App Lock is enabled", () => { const settings = readFileSync(new URL("../components/AppLockSettings.tsx", import.meta.url), "utf8"); assert.match(settings, /!lock\.enabled \?[^:]+appLock\.setup[\s\S]*: <>[\s\S]*appLock\.forgot/); const forgotCount = settings.match(/t\("appLock\.forgot"\)/g)?.length ?? 0; assert.equal(forgotCount, 1); });
test("Security Center treats disabled lock as optional attention, never wallet compromise", () => { assert.deepEqual(appLockRecommendation("enabled"), { severity: "info", label: "Local App Lock enabled" }); assert.deepEqual(appLockRecommendation("disabled"), { severity: "attention", label: "Optional App Lock is disabled" }); assert.doesNotMatch(appLockRecommendation("disabled").label, /compromised/i); });

class MemoryStorage {
  private data = new Map<string, string>(); constructor(initial: Record<string, string>) { for (const entry of Object.entries(initial)) this.data.set(...entry); }
  get length() { return this.data.size; } key(index: number) { return [...this.data.keys()][index] ?? null; } getItem(key: string) { return this.data.get(key) ?? null; } setItem(key: string, value: string) { this.data.set(key, value); } removeItem(key: string) { this.data.delete(key); }
}

function unlocked(config: AppLockConfig): AppLockSessionState { return { config, locked: false }; }
function syncConfig(state: AppLockSessionState, config?: AppLockConfig) { return syncAppLockStorageEvent(state, APP_LOCK_STORAGE_KEY, config ? JSON.stringify(config) : null, null); }
function syncSignal(state: AppLockSessionState, config: AppLockConfig | undefined, action: "lock" | "disable" | "reset") { return syncAppLockStorageEvent(state, APP_LOCK_SIGNAL_KEY, config ? JSON.stringify(config) : null, JSON.stringify({ action, at: 1 })); }
