import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { arcFeeToUsdcAtomic } from "./arcFees.ts";
import { calculateSafeUsdcSwapMax, SAFE_MAX_FINAL_VERIFY_ATTEMPTS, SAFE_MAX_MAX_ITERATIONS, SAFE_MAX_SOLVE_ATTEMPTS, SafeSwapMaxError } from "./safeSwapMax.ts";
import { safeMaxCanUseSwapEstimate } from "./swapApprovalFlow.ts";

const flow = readFileSync(new URL("../components/RealSwapFlow.tsx", import.meta.url), "utf8");
const solver = readFileSync(new URL("./safeSwapMax.ts", import.meta.url), "utf8");

test("1 insufficient allowance asks for approval first", () => assert.equal(safeMaxCanUseSwapEstimate(9n, 10n), false));
test("2 sufficient allowance calculates MAX", async () => assert.deepEqual((await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: 7n }))).amount, 93n));
test("3 initial full-balance estimate failure recovers with bounded backoff", async () => { const result = await calculateSafeUsdcSwapMax(100n, async (candidate) => { if (candidate === 100n) throw new Error("insufficient funds for gas"); return { feeUsdc6: 7n }; }); assert.equal(result.amount, 93n); assert.equal(result.usedBackoff, true); });
test("4 final candidate is below wallet balance", async () => assert.ok((await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: 3n }))).amount < 100n));
test("5 final candidate plus real fee fits balance", async () => { const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: 9n })); assert.ok(result.amount + result.feeUsdc6 <= 100n); });
test("6 solver contains no arbitrary fixed reserve", () => { assert.doesNotMatch(solver, /0\.01|percent|percentage/); assert.match(solver, /balance - maxObservedFee/); });
test("7 convergence terminates within the fixed bound", async () => assert.ok((await calculateSafeUsdcSwapMax(1_000n, async () => ({ feeUsdc6: 11n }))).iterations <= SAFE_MAX_MAX_ITERATIONS));
test("8 changing gas prices do not cause no-convergence", async () => { let call = 0; const fees = [4_600n, 4_680n, 4_630n, 4_710n, 4_690n]; const result = await calculateSafeUsdcSwapMax(1_000_000n, async () => ({ feeUsdc6: fees[Math.min(call++, fees.length - 1)] })); assert.ok(result.amount > 0n); });
test("9 oscillating fees produce a safe conservative result", async () => { let call = 0; const fees = [10n, 14n, 11n, 15n, 12n]; const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: fees[Math.min(call++, fees.length - 1)] })); assert.ok(result.amount + result.feeUsdc6 <= 100n); assert.ok(result.amount <= 86n); });
test("9a monotonically increasing fees reduce MAX", async () => { let call = 0; const fees = [5n, 6n, 7n, 8n, 9n, 10n, 10n]; const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: fees[Math.min(call++, fees.length - 1)] })); assert.equal(result.amount, 90n); assert.ok(result.amount + result.feeUsdc6 <= 100n); });
test("9b decreasing fees never reclaim the conservative reserve", async () => { let call = 0; const fees = [10n, 9n, 8n, 7n]; const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: fees[Math.min(call++, fees.length - 1)] })); assert.equal(result.amount, 90n); });
test("9c a higher final live fee reduces MAX", async () => { const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: 5n }), async () => ({ feeUsdc6: 8n })); assert.equal(result.amount, 92n); assert.equal(result.feeUsdc6, 8n); });
test("9d a lower final live fee keeps the conservative amount", async () => { const result = await calculateSafeUsdcSwapMax(100n, async () => ({ feeUsdc6: 8n }), async () => ({ feeUsdc6: 5n })); assert.equal(result.amount, 92n); assert.equal(result.feeUsdc6, 5n); });
test("9e solve exhaustion retains independent final verification capacity", async () => { let solveCalls = 0, finalCalls = 0; const result = await calculateSafeUsdcSwapMax(1_000n, async () => ({ feeUsdc6: 10n + BigInt(solveCalls++) }), async () => { finalCalls += 1; return { feeUsdc6: 20n }; }); assert.equal(solveCalls, SAFE_MAX_SOLVE_ATTEMPTS); assert.ok(finalCalls > 0 && finalCalls <= SAFE_MAX_FINAL_VERIFY_ATTEMPTS); assert.ok(result.amount + result.feeUsdc6 <= 1_000n); });
test("9h realistic Arc fee units are normalized before SAFE MAX arithmetic", async () => { const balanceUsdc6 = 34_937_289n, rawFee18 = 4_887_000_000_000_000n, feeUsdc6 = arcFeeToUsdcAtomic(rawFee18); assert.equal(feeUsdc6, 4_887n); const result = await calculateSafeUsdcSwapMax(balanceUsdc6, async () => ({ feeUsdc6 })); assert.equal(result.amount, 34_932_402n); assert.ok(result.amount > 0n && result.amount < balanceUsdc6); assert.ok(result.amount + result.feeUsdc6 <= balanceUsdc6); });
test("9i component converts raw Arc fee exactly once at the solver boundary", () => { assert.match(flow, /return \{ feeUsdc6: arcFeeToUsdcAtomic\(rawFee18\) \}/); assert.match(flow, /formatAssetAmount\(safeMax\.feeUsdc6/); assert.doesNotMatch(flow, /arcFeeToUsdcAtomic\(safeMax\./); });
test("9f fixed solve snapshot and fresh final estimator remain separate", () => { assert.match(flow, /const fixedFeePerGas = await gasPrice\(\)/); assert.match(flow, /estimateCandidate\(candidate, fixedFeePerGas\)/); assert.match(flow, /estimateCandidate\(candidate\)\)/); });
test("9g state override fallback remains estimation-only", () => { assert.match(flow, /stateOverride: \[\{ address: connection\.address, balance:/); assert.match(flow, /useNativeBalanceOverride = false/); assert.doesNotMatch(flow.slice(flow.indexOf("async function execute")), /stateOverride/); });
test("10 balance changes invalidate MAX", () => assert.match(flow, /safeMax\.balance === balance/));
test("11 account changes invalidate MAX", () => assert.match(flow, /safeMax\.account\.toLowerCase\(\) === connection\.address/));
test("12 chain changes invalidate MAX", () => assert.match(flow, /safeMax\.chainId === arcTestnet\.id && chain\.isArc/));
test("13 tiny balance returns truthful unable state", async () => await assert.rejects(calculateSafeUsdcSwapMax(1n, async () => ({ feeUsdc6: 1n })), (error: unknown) => error instanceof SafeSwapMaxError && error.code === "too-small"));
test("14 zero balance is rejected", async () => await assert.rejects(calculateSafeUsdcSwapMax(0n, async () => ({ feeUsdc6: 1n })), (error: unknown) => error instanceof SafeSwapMaxError && error.code === "zero-balance"));
test("15 MAX calculation performs no wallet write", () => { const maxBody = flow.slice(flow.indexOf("async function chooseQuickAmount"), flow.indexOf("async function approveForMax")); assert.doesNotMatch(maxBody, /writeContract|simulateContract/); });
test("16 normal quick percentages remain unchanged", () => assert.match(flow, /\[25, 50, 75, 100\]/));
test("17 approval-first flow remains separate", () => { assert.match(flow, /approveThenReview/); assert.match(flow, /setReviewStage\("swap"\)/); });
test("18 USDC to EURC remains supported", () => assert.match(flow, /oppositeAssetId\(fromId\)/));
test("19 EURC to USDC remains supported", () => assert.match(flow, /SUPPORTED_ASSETS/));
