import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createSwapFeeEnvelope, isSwapFeeWithinEnvelope, selectSwapGasLimit } from "./swapFeeEnvelope.ts";

const flow = readFileSync(new URL("../components/RealSwapFlow.tsx", import.meta.url), "utf8");
test("wallet-provider gas wins when larger", () => assert.equal(selectSwapGasLimit(100n, 120n).gasLimit, 120n));
test("public RPC gas wins when larger", () => assert.equal(selectSwapGasLimit(120n, 100n).gasLimit, 120n));
test("wallet-provider unavailable uses deterministic gas-unit headroom", () => assert.equal(selectSwapGasLimit(100n).gasLimit, 110n));
test("maximum envelope is gas limit times max fee per gas", () => assert.equal(createSwapFeeEnvelope(100n, 120n, 7n).rawMaxFee18, 840n));
test("envelope converts to USDC6 exactly once", () => assert.equal(createSwapFeeEnvelope(100_000n, undefined, 40_000_000_000n).feeUsdc6, 4_400n));
test("fresh fee lower than reviewed envelope remains valid", () => assert.equal(isSwapFeeWithinEnvelope(createSwapFeeEnvelope(120n, undefined, 10n, 3n), createSwapFeeEnvelope(100n, undefined, 8n, 2n)), true));
test("fresh fee equal to reviewed envelope remains valid", () => { const envelope = createSwapFeeEnvelope(100n, undefined, 7n, 2n); assert.equal(isSwapFeeWithinEnvelope(envelope, envelope), true); });
test("small gas and EIP-1559 drift inside envelope remains valid", () => assert.equal(isSwapFeeWithinEnvelope(createSwapFeeEnvelope(100n, 120n, 10n, 4n), createSwapFeeEnvelope(105n, 110n, 9n, 3n)), true));
test("priority-fee drift stays valid when aggregate caps remain inside the envelope", () => assert.equal(isSwapFeeWithinEnvelope(createSwapFeeEnvelope(100n, undefined, 10n, 2n), createSwapFeeEnvelope(90n, undefined, 9n, 8n)), true));
test("fee above reviewed envelope requires review again", () => { const reviewed = createSwapFeeEnvelope(100n, undefined, 10n, 3n); assert.equal(isSwapFeeWithinEnvelope(reviewed, createSwapFeeEnvelope(111n, undefined, 10n, 3n)), false); assert.equal(isSwapFeeWithinEnvelope(reviewed, createSwapFeeEnvelope(100n, undefined, 11n, 3n)), false); });
test("explicit reviewed EIP-1559 caps reach submitted request", () => { assert.match(flow, /gas: swapEnvelope\.gasLimit/); assert.match(flow, /maxFeePerGas: swapEnvelope\.maxFeePerGas/); assert.match(flow, /maxPriorityFeePerGas: swapEnvelope\.maxPriorityFeePerGas/); });
test("wallet estimation is read-only", () => { assert.match(flow, /method: "eth_estimateGas"/); assert.doesNotMatch(flow.slice(flow.indexOf("async function solveSafeMax"), flow.indexOf("async function chooseQuickAmount")), /writeContract/); });
test("final MAX check runs before wallet submission", () => { assert.ok(flow.indexOf("freshEnvelope.feeUsdc6 > freshBalance") < flow.indexOf("writer.writeContractAsync(simulation.request)")); });
test("no fixed USDC reserve", () => assert.doesNotMatch(readFileSync(new URL("./swapFeeEnvelope.ts", import.meta.url), "utf8"), /0\.01|10_000n \/ 1_000_000n/));
test("post-approval fresh swap review is retained", () => { const postApproval = flow.slice(flow.indexOf("async function approveThenReview"), flow.indexOf("async function execute")); assert.match(postApproval, /setSwapReview\(prepareFlowReview/); assert.doesNotMatch(postApproval, /setSwapReview\(undefined\)/); });
test("Continue to wallet invokes exactly one guarded wallet request", () => { const execute = flow.slice(flow.indexOf("async function execute"), flow.indexOf("if \(success\)")); assert.equal(execute.match(/writer\.writeContractAsync/g)?.length, 1); assert.match(execute, /submissionGuard\.current\.run/); });
test("wallet rejection releases the guard", () => { const source = readFileSync(new URL("./transactionOrchestrator.ts", import.meta.url), "utf8"); assert.match(source, /finally \{ this\.#active\.delete\(fingerprint\); \}/); });
