import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { encodeFunctionData, maxUint256, type Address } from "viem";
import { arcTestnet, baseSepolia } from "viem/chains";
import { penguJarV3Abi } from "./abi/penguJarV3.ts";
import { getAssetById } from "./assets.ts";
import { contractAddress } from "./config.ts";
import { XYLO_ROUTER } from "./swap.ts";
import { approvalIntent, bridgeIntent, managedRequest, prepareFlowReview, swapIntent, vaultIntent } from "./transactionFlowReview.ts";
import { revalidateTransactionReview } from "./transactionOrchestrator.ts";
import { assessTransaction, type SafetyContext } from "./transactionSafety.ts";

const account = "0x1111111111111111111111111111111111111111" as Address, recipient = "0x2222222222222222222222222222222222222222" as Address;
const usdc = getAssetById("usdc")!;
const context: SafetyContext = { connectedAccount: account, connectedChainId: arcTestnet.id, balances: { usdc: 10_000_000n, eurc: 10_000_000n }, allowance: 1_000_000n, simulation: "passed", now: 1_000, expectedTarget: XYLO_ROUTER };
const swap = swapIntent({ id: "swap", account, target: XYLO_ROUTER, calldata: "0x1234", preparedAt: 1_000, expiresAt: 61_000, inputAsset: "usdc", outputAsset: "eurc", amount: 1_000_000n, quoteOutput: 990_000n, minimumReceive: 980_000n, slippageBps: 50, route: "xylonet", gas: { gasLimit: 100_000n, maxFeePerGas: 2n, maxFeeRaw18: 200_000n, maxFeeUsdc6: 1n } });

test("swap uses a snapshot binding route, expiry, minimum receive and fee envelope", () => { const review = prepareFlowReview(swap, context); assert.equal(review.intent.kind, "swap"); for (const changed of [{ ...swap, account: recipient }, { ...swap, metadata: { ...swap.metadata, route: "other" } }, { ...swap, assetIn: { ...swap.assetIn!, minimumAmount: 970_000n } }]) assert.equal(revalidateTransactionReview(review, { intent: changed, context, now: 2_000 }).valid, false); assert.deepEqual(revalidateTransactionReview(review, { intent: swap, context, now: 61_001 }), { valid: false, reason: "expired" }); });
test("finite exact approval snapshots and unlimited approval remains blocked", () => { const approval = approvalIntent({ id: "approval", account, target: usdc.address, token: usdc.address, spender: XYLO_ROUTER, amount: 1_000_000n, assetId: "usdc", calldata: "0x", preparedAt: 1_000, gas: { gasLimit: 50_000n, maxFeeRaw18: 1n, maxFeeUsdc6: 1n } }); const review = prepareFlowReview(approval, { ...context, expectedTarget: usdc.address, allowance: 0n }); assert.equal(review.intent.approval?.amount, 1_000_000n); assert.equal(review.intent.approval?.finite, true); assert.equal(assessTransaction({ ...approval, approval: { ...approval.approval!, amount: maxUint256, finite: false } }, { ...context, expectedTarget: usdc.address }).status, "blocked"); });
test("Circle-managed Universal Bridge snapshot binds account and estimate expiry truthfully", () => { const intent = bridgeIntent({ id: "circle", account, chainId: baseSepolia.id, target: usdc.address, calldata: "0x", preparedAt: 1_000, expiresAt: 46_000, assetId: "usdc", amount: 1_000_000n, recipient, destinationChainId: arcTestnet.id, route: "circle-app-kit-cctp", expectedReceive: 990_000n, forwardingFee: "0.01", circleManaged: true }); const managedContext: SafetyContext = { connectedAccount: account, connectedChainId: baseSepolia.id, balances: { usdc: 2_000_000n }, simulation: "passed", now: 1_000, managedTarget: { label: "Circle App Kit", category: "circle" } }; const review = prepareFlowReview(intent, managedContext, managedRequest(intent)); assert.equal(review.intent.metadata?.finalTransaction, "managed-by-circle-app-kit"); assert.equal(revalidateTransactionReview(review, { intent: { ...intent, account: recipient }, context: managedContext, request: managedRequest(intent), now: 2_000 }).valid, false); assert.equal(revalidateTransactionReview(review, { intent, context: managedContext, request: managedRequest(intent), now: 46_001 }).valid, false); });
test("CCTP total burn and fee expiry are material", () => { const intent = bridgeIntent({ id: "cctp", account, target: usdc.address, calldata: "0x1234", preparedAt: 1_000, expiresAt: 46_000, assetId: "usdc", amount: 1_020_000n, recipient: account, destinationChainId: baseSepolia.id, route: "cctp-direct", forwardingFee: "10000", protocolFee: "10000" }); const ctx = { ...context, expectedTarget: usdc.address }; const review = prepareFlowReview(intent, ctx); assert.equal(revalidateTransactionReview(review, { intent: { ...intent, assetOut: { assetId: "usdc", amount: 1_030_000n } }, context: ctx, now: 2_000 }).valid, false); assert.equal(revalidateTransactionReview(review, { intent, context: ctx, now: 46_001 }).valid, false); });
test("Vault deposit and withdrawal snapshots bind configured target and exact calldata", () => { assert.ok(contractAddress); const depositData = encodeFunctionData({ abi: penguJarV3Abi, functionName: "depositToJar", args: [1n, 1_000_000n] }), withdrawData = encodeFunctionData({ abi: penguJarV3Abi, functionName: "withdrawJar", args: [1n] }); for (const intent of [vaultIntent({ id: "deposit", kind: "vault-deposit", account, target: contractAddress!, calldata: depositData, preparedAt: 1_000, assetId: "usdc", amount: 1_000_000n, jarId: 1n }), vaultIntent({ id: "withdraw", kind: "vault-withdraw", account, target: contractAddress!, calldata: withdrawData, preparedAt: 1_000, assetId: "usdc", amount: 1_000_000n, jarId: 1n })]) { const ctx = { ...context, expectedTarget: contractAddress! }; const review = prepareFlowReview(intent, ctx); assert.equal(revalidateTransactionReview(review, { intent: { ...intent, target: recipient }, context: ctx, now: 2_000 }).valid, false); } });
test("all target components import and call the unified orchestrator", () => { for (const file of ["RealSwapFlow.tsx", "UniversalBridgeFlow.tsx", "CctpBridgeFlow.tsx", "OwnerDepositFlow.tsx", "OwnerWithdrawalFlow.tsx"]) { const source = readFileSync(new URL(`../components/${file}`, import.meta.url), "utf8"); assert.match(source, /prepareFlowReview/); assert.match(source, /revalidateTransactionReview/); assert.match(source, /ReviewSubmissionGuard/); } });
