import assert from "node:assert/strict";
import test from "node:test";
import { encodeFunctionData, maxUint256, type Address, type Hex } from "viem";
import { arcTestnet } from "viem/chains";
import { erc20BalanceAbi } from "./abi/erc20.ts";
import { ARC_MEMO_ADDRESS } from "./arcMemo.ts";
import { getAssetById } from "./assets.ts";
import { CCTP_TOKEN_MESSENGER_V2 } from "./cctp.ts";
import { contractAddress } from "./config.ts";
import { findKnownContract } from "./knownContracts.ts";
import { XYLO_ROUTER } from "./swap.ts";
import { assessTransaction, assertReviewedRequest, expectedTransactionChanges, transactionFingerprint, type SafetyContext, type TransactionIntent } from "./transactionSafety.ts";

const account = "0x1111111111111111111111111111111111111111" as Address, recipient = "0x2222222222222222222222222222222222222222" as Address;
const usdc = getAssetById("usdc")!, eurc = getAssetById("eurc")!;
const calldata = encodeFunctionData({ abi: erc20BalanceAbi, functionName: "transfer", args: [recipient, 1_000_000n] });
const base: TransactionIntent = { id: "send-1", kind: "send", chainId: arcTestnet.id, account, target: usdc.address, calldata, value: 0n, recipient, assetOut: { assetId: "usdc", amount: 1_000_000n }, gas: { gasLimit: 50_000n, maxFeePerGas: 1_000_000n, maxFeeRaw18: 50_000_000_000n, maxFeeUsdc6: 1n }, preparedAt: 1_000 };
const context: SafetyContext = { connectedAccount: account, connectedChainId: arcTestnet.id, balances: { usdc: 2_000_000n }, simulation: "passed", now: 2_000, expectedTarget: usdc.address };
const assess = (intent: TransactionIntent = base, overrides: Partial<SafetyContext> = {}) => assessTransaction(intent, { ...context, ...overrides });

test("correct Arc chain, matching account, known target and simulation are ready", () => assert.equal(assess().status, "ready"));
test("wrong chain blocks", () => assert.equal(assess(base, { connectedChainId: 1 }).status, "blocked"));
test("account change blocks", () => assert.equal(assess(base, { connectedAccount: recipient }).blockers.some((x) => x.code === "account-match"), true));
test("invalid and zero recipients block", () => { const zero = { ...base, recipient: "0x0000000000000000000000000000000000000000" as Address }; assert.equal(assess(zero).status, "blocked"); });
test("known USDC and EURC contracts are recognized", () => { assert.equal(findKnownContract(usdc.address, arcTestnet.id)?.category, "token"); assert.equal(findKnownContract(eurc.address, arcTestnet.id)?.category, "token"); });
test("known Xylo, Vault, Memo and Circle targets are registry backed", () => { assert.equal(findKnownContract(XYLO_ROUTER, arcTestnet.id)?.label, "XyloNet Router"); assert.equal(contractAddress && findKnownContract(contractAddress, arcTestnet.id)?.label, "Makoto Vault"); assert.equal(findKnownContract(ARC_MEMO_ADDRESS, arcTestnet.id)?.label, "Arc Transaction Memo"); assert.equal(findKnownContract(CCTP_TOKEN_MESSENGER_V2, arcTestnet.id)?.category, "circle"); });
test("unexpected unknown target blocks a Makoto integration flow", () => { const unknown = "0x3333333333333333333333333333333333333333" as Address; assert.equal(assess({ ...base, target: unknown }, { expectedTarget: usdc.address }).status, "blocked"); });
test("unknown target without an expected integration is unknown, never malicious", () => { const unknown = "0x3333333333333333333333333333333333333333" as Address; assert.equal(assess({ ...base, target: unknown }, { expectedTarget: undefined }).status, "unknown"); });
test("exact simulation passes and revert blocks", () => { assert.equal(assess().checks.find((x) => x.code === "request-simulated")?.status, "pass"); assert.equal(assess(base, { simulation: "reverted" }).status, "blocked"); });
test("amount above balance and amount plus fee above balance block", () => { assert.equal(assess(base, { balances: { usdc: 999_999n } }).status, "blocked"); assert.equal(assess({ ...base, assetOut: { assetId: "usdc", amount: 2_000_000n } }).blockers.some((x) => x.code === "gas-covered"), true); });
test("raw 18-decimal fee is preserved and only converted USDC6 enters balance comparison", () => { const intent = { ...base, gas: { ...base.gas!, maxFeeRaw18: 900_000_000_000_000n, maxFeeUsdc6: 900n } }; assert.equal(assess(intent, { balances: { usdc: 1_000_900n } }).status, "ready"); assert.equal(intent.gas.maxFeeRaw18, 900_000_000_000_000n); });
test("finite approval passes and unlimited approval blocks", () => { const finite = { ...base, kind: "approval" as const, approval: { token: usdc.address, spender: XYLO_ROUTER, amount: 1_000_000n, finite: true } }; assert.equal(assess(finite, { allowance: 0n }).status, "review"); assert.equal(assess({ ...finite, approval: { ...finite.approval, amount: maxUint256, finite: false } }).status, "blocked"); });
test("sufficient allowance reports no approval required", () => { const intent = { ...base, approval: { token: usdc.address, spender: XYLO_ROUTER, amount: 1_000_000n, finite: true } }; assert.equal(assess(intent, { allowance: 1_000_000n }).checks.find((x) => x.code === "allowance-sufficient")?.message, "No approval required"); });
test("expired quote blocks and fresh quote passes", () => { assert.equal(assess({ ...base, quoteExpiresAt: 1_999 }).status, "blocked"); assert.equal(assess({ ...base, quoteExpiresAt: 2_001 }).status, "ready"); });
test("minimum receive and slippage are fingerprint material", () => { const swap = { ...base, kind: "swap" as const, target: XYLO_ROUTER, assetIn: { assetId: "eurc" as const, expectedAmount: 900_000n, minimumAmount: 890_000n }, metadata: { slippageBps: 100 }, quoteExpiresAt: 3_000 }; assert.notEqual(transactionFingerprint(swap), transactionFingerprint({ ...swap, assetIn: { ...swap.assetIn, minimumAmount: 880_000n } })); assert.notEqual(transactionFingerprint(swap), transactionFingerprint({ ...swap, metadata: { slippageBps: 200 } })); });
test("identical requests have stable reviewed fingerprints", () => assert.equal(transactionFingerprint(base), transactionFingerprint({ ...base })));
test("amount, recipient, calldata, account and chain invalidate fingerprint", () => { const fingerprint = transactionFingerprint(base); for (const changed of [{ ...base, assetOut: { assetId: "usdc" as const, amount: 2n } }, { ...base, recipient: account }, { ...base, calldata: "0x1234" as Hex }, { ...base, account: recipient }, { ...base, chainId: 1 }]) assert.notEqual(transactionFingerprint(changed), fingerprint); });
test("gas envelope material change invalidates fingerprint", () => assert.notEqual(transactionFingerprint(base), transactionFingerprint({ ...base, gas: { ...base.gas!, maxFeeUsdc6: 2n } })));
test("final pre-wallet assertion blocks changed requests", () => { const fingerprint = transactionFingerprint(base); assert.doesNotThrow(() => assertReviewedRequest(base, fingerprint)); assert.throws(() => assertReviewedRequest({ ...base, calldata: "0x12" }, fingerprint), /Review again/); });
test("bridge Circle-managed fields remain safe JSON metadata", () => { const bridge = { ...base, kind: "bridge" as const, target: CCTP_TOKEN_MESSENGER_V2, metadata: { provider: "Circle App Kit", finalTransaction: "managed-by-circle-app-kit" } }; assert.equal(assessTransaction(bridge, { ...context, expectedTarget: CCTP_TOKEN_MESSENGER_V2 }).status, "ready"); });
test("Vault deposit and withdrawal intents recognize configured Vault", () => { assert.ok(contractAddress); const deposit = { ...base, kind: "vault-deposit" as const, target: contractAddress! }, withdrawal = { ...base, kind: "vault-withdraw" as const, target: contractAddress!, assetOut: undefined, assetIn: { assetId: "usdc" as const, minimumAmount: 1n } }; assert.equal(assessTransaction(deposit, { ...context, expectedTarget: contractAddress! }).target?.label, "Makoto Vault"); assert.equal(assessTransaction(withdrawal, { ...context, expectedTarget: contractAddress! }).status, "ready"); });
test("expected changes preserve exact out, minimum in and maximum converted fee semantics", () => { const changes = expectedTransactionChanges({ ...base, assetIn: { assetId: "eurc", expectedAmount: 900_000n, minimumAmount: 890_000n } }); assert.deepEqual(changes.map((x) => [x.assetId, x.direction, x.qualifier]), [["usdc", "decrease", "exact"], ["eurc", "increase", "minimum"], ["usdc", "decrease", "maximum"]]); });
