import { encodeFunctionData, type Address, type Hex } from "viem";
import { arcTestnet } from "viem/chains";
import { erc20BalanceAbi } from "./abi/erc20.ts";
import type { SupportedAssetId } from "./assets.ts";
import { prepareTransactionReview, requestFromIntent, type TransactionRequestInput, type TransactionReviewSnapshot } from "./transactionOrchestrator.ts";
import type { SafetyContext, TransactionIntent } from "./transactionSafety.ts";

type Base = { id: string; account: Address; chainId?: number; target: Address; calldata: Hex; preparedAt: number; expiresAt?: number; gas?: TransactionIntent["gas"]; metadata?: TransactionIntent["metadata"] };
export function approvalIntent(input: Base & { token: Address; spender: Address; amount: bigint; assetId: SupportedAssetId }): TransactionIntent { return { ...base(input), kind: "approval", target: input.token, calldata: encodeFunctionData({ abi: erc20BalanceAbi, functionName: "approve", args: [input.spender, input.amount] }), approval: { token: input.token, spender: input.spender, amount: input.amount, finite: true }, metadata: input.metadata }; }
export function swapIntent(input: Base & { inputAsset: SupportedAssetId; outputAsset: SupportedAssetId; amount: bigint; quoteOutput: bigint; minimumReceive: bigint; slippageBps: number; route: string }): TransactionIntent { return { ...base(input), kind: "swap", assetOut: { assetId: input.inputAsset, amount: input.amount }, assetIn: { assetId: input.outputAsset, expectedAmount: input.quoteOutput, minimumAmount: input.minimumReceive }, quoteExpiresAt: input.expiresAt, metadata: { ...input.metadata, route: input.route, slippageBps: input.slippageBps } }; }
export function bridgeIntent(input: Base & { assetId: SupportedAssetId; amount: bigint; recipient: Address; destinationChainId: number; route: string; expectedReceive?: bigint; forwardingFee?: string; protocolFee?: string; circleManaged?: boolean }): TransactionIntent { return { ...base(input), kind: "bridge", recipient: input.recipient, assetOut: { assetId: input.assetId, amount: input.amount }, quoteExpiresAt: input.expiresAt, metadata: { ...input.metadata, destinationChainId: input.destinationChainId, route: input.route, ...(input.expectedReceive === undefined ? {} : { expectedReceive: input.expectedReceive.toString() }), ...(input.forwardingFee === undefined ? {} : { forwardingFee: input.forwardingFee }), ...(input.protocolFee === undefined ? {} : { protocolFee: input.protocolFee }), finalTransaction: input.circleManaged ? "managed-by-circle-app-kit" : "exact-calldata" } }; }
export function vaultIntent(input: Base & { kind: "vault-deposit" | "vault-withdraw"; assetId: SupportedAssetId; amount: bigint; jarId: bigint }): TransactionIntent { return { ...base(input), kind: input.kind, ...(input.kind === "vault-deposit" ? { assetOut: { assetId: input.assetId, amount: input.amount } } : { assetIn: { assetId: input.assetId, expectedAmount: input.amount } }), metadata: { ...input.metadata, jarId: input.jarId.toString() } }; }
export function prepareFlowReview(intent: TransactionIntent, context: SafetyContext, request: TransactionRequestInput = requestFromIntent(intent)): TransactionReviewSnapshot { return prepareTransactionReview({ intent, context, request, preparedAt: intent.preparedAt, expiresAt: intent.quoteExpiresAt }); }
export function managedRequest(intent: TransactionIntent): TransactionRequestInput { return { to: intent.target, data: "0x", value: 0n, chainId: intent.chainId }; }
function base(input: Base): TransactionIntent { return { id: input.id, kind: "send", chainId: input.chainId ?? arcTestnet.id, account: input.account, target: input.target, calldata: input.calldata, value: 0n, preparedAt: input.preparedAt, gas: input.gas, metadata: input.metadata }; }
