import assert from "node:assert/strict";
import test from "node:test";
import { createReviewedSpend, reviewedSpendMatches, sanitizeSpendError, selectSpendAllocations, spendFeeLabel, spendFeesChanged, spendFeeTotalUsdc } from "./circle/unifiedBalance.ts";
import type { UnifiedBalance } from "./circle/types.ts";

const wallet="0x1111111111111111111111111111111111111111";
const recipient="0x2222222222222222222222222222222222222222";
const balance=(arc:bigint,base:bigint):UnifiedBalance=>({available:arc+base,pending:0n,total:arc+base,sources:[{domain:26,chain:"Arc_Testnet",amount:arc},{domain:6,chain:"Base_Sepolia",amount:base}]});
const fees=[{type:"provider" as const,token:"USDC",amount:"0.000005",allocations:[]},{type:"gasFee" as const,token:"USDC",amount:"0.024287",allocations:[{chain:"Base_Sepolia",amount:"0.024287"}]},{type:"forwarder" as const,token:"USDC",amount:"0.014292",allocations:[]}];

test("Base-only and Arc-only balances create exact explicit transfer allocations",()=>{assert.deepEqual(selectSpendAllocations(balance(0n,1_100_000n),"0.10"),[{chain:"Base_Sepolia",amount:"0.1"}]);assert.deepEqual(selectSpendAllocations(balance(1_100_000n,0n),"0.10"),[{chain:"Arc_Testnet",amount:"0.1"}])});
test("multi-source selection is deterministic when no single source is sufficient",()=>{assert.deepEqual(selectSpendAllocations(balance(60_000n,50_000n),"0.10"),[{chain:"Arc_Testnet",amount:"0.06"},{chain:"Base_Sepolia",amount:"0.04"}])});
test("1.1 USDC supports a 0.10 allocation without adding fees to transfer amount",()=>{assert.doesNotThrow(()=>selectSpendAllocations(balance(0n,1_100_000n),"0.10"));assert.equal(selectSpendAllocations(balance(0n,1_100_000n),"0.10")[0].amount,"0.1")});
test("review fingerprint covers account, recipient, amount, destination, and forwarder mode",()=>{const review=createReviewedSpend({account:wallet,recipient,amount:"0.10",destination:"Arc_Testnet",useForwarder:true,allocations:[{chain:"Base_Sepolia",amount:"0.1"}],quotedAt:1,fees});const input={account:wallet,recipient,amount:"0.10",destination:"Arc_Testnet",useForwarder:true};assert.equal(reviewedSpendMatches(review,input),true);assert.equal(reviewedSpendMatches(review,{...input,account:recipient}),false);assert.equal(reviewedSpendMatches(review,{...input,recipient:wallet}),false);assert.equal(reviewedSpendMatches(review,{...input,amount:"0.11"}),false);assert.equal(reviewedSpendMatches(review,{...input,destination:"Base_Sepolia"}),false);assert.equal(reviewedSpendMatches(review,{...input,useForwarder:false}),false)});
test("fee drift invalidates review while reordered equivalent fees do not",()=>{assert.equal(spendFeesChanged(fees,[...fees].reverse()),false);assert.equal(spendFeesChanged(fees,fees.map(f=>f.type==="forwarder"?{...f,amount:"0.015446"}:f)),true)});
test("forwarding maxFee errors become friendly EN and VI messages",()=>{const error=new Error("Gateway API error: HTTP 400 — Insufficient total maxFee across intents to cover forwarding fee. Required additional: 0.001154");assert.equal(sanitizeSpendError(error),"Forwarding fee changed before submission. Please estimate again.");assert.equal(sanitizeSpendError(error,true),"Phí chuyển tiếp đã thay đổi trước khi gửi. Vui lòng ước tính lại.")});
test("fee labels are localized and only USDC entries enter the displayed total",()=>{assert.equal(spendFeeLabel("provider",false),"Provider fee");assert.equal(spendFeeLabel("gasFee",true),"Gas ước tính");assert.equal(spendFeeLabel("forwarder",true),"Phí chuyển tiếp");assert.equal(spendFeeTotalUsdc([...fees,{type:"gasFee",token:"ETH",amount:"1",allocations:[]}]),38_584n)});
